import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ProductDto } from '../models/product.dto';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  getProducts(): Observable<ProductDto[]> {
    const dummyDtos: ProductDto[] = [
      {
        id: 1,
        id_aoldatabase: 101,
        id_aoldb: 1,
        id_vendor: 5,
        id_produkbrand: 2,
        id_produkkategori: 10,
        id_aolprod: 501,
        nama_vendor_produk: 'PT Asus Indonesia',
        nama_brand_produk: 'ROG',
        nama_kategori_produk: 'Laptop',
        nomor_produk: 'PRD-001',
        nama_produk: 'Laptop Gaming ROG Strix G16',
        jenis_produk: 'Barang',
        barcode_produk: '899123456789',
        keterangan_produk: 'High performance gaming laptop',
        aktif_produk: true,
        konversi_unit1: 1,
        konversi_unit2: 0,
        konversi_unit3: 0,
        konversi_unit4: 0,
        konversi_unit5: 0,
        rasio_unit1: 1,
        rasio_unit2: 1,
        rasio_unit3: 1,
        rasio_unit4: 1,
        rasio_unit5: 1,
        gramasi_produk: 2500,
        panjang_produk_kecil: 35,
        lebar_produk_kecil: 25,
        tinggi_produk_kecil: 3,
        panjang_produk_besar: 45,
        lebar_produk_besar: 35,
        tinggi_produk_besar: 10,
        gambar_produk: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302',
        minim_beli_unit1: 1,
        minim_stok_unit1: 2,
        log_aolcat_id: 1,
        log_aolven_id: 1,
        created_at: '2026-07-22T08:00:00Z',
        updated_at: '2026-07-22T08:00:00Z',
        deleted_at: null
      },
      {
        id: 2,
        id_aoldatabase: 102,
        id_aoldb: 1,
        id_vendor: 6,
        id_produkbrand: 3,
        id_produkkategori: 11,
        id_aolprod: 502,
        nama_vendor_produk: 'PT Samsung Electronics',
        nama_brand_produk: 'Samsung',
        nama_kategori_produk: 'Smartphone',
        nomor_produk: 'PRD-002',
        nama_produk: 'Samsung Galaxy S24 Ultra 512GB',
        jenis_produk: 'Barang',
        barcode_produk: '899876543210',
        keterangan_produk: 'Flagship smartphone dengan Galaxy AI',
        aktif_produk: true,
        konversi_unit1: 1,
        konversi_unit2: 0,
        konversi_unit3: 0,
        konversi_unit4: 0,
        konversi_unit5: 0,
        rasio_unit1: 1,
        rasio_unit2: 1,
        rasio_unit3: 1,
        rasio_unit4: 1,
        rasio_unit5: 1,
        gramasi_produk: 232,
        panjang_produk_kecil: 16,
        lebar_produk_kecil: 7.9,
        tinggi_produk_kecil: 0.86,
        panjang_produk_besar: 20,
        lebar_produk_besar: 12,
        tinggi_produk_besar: 5,
        gambar_produk: '',
        minim_beli_unit1: 1,
        minim_stok_unit1: 5,
        log_aolcat_id: 2,
        log_aolven_id: 2,
        created_at: '2026-07-22T09:00:00Z',
        updated_at: '2026-07-22T09:00:00Z',
        deleted_at: null
      },
      {
        id: 3,
        id_aoldatabase: 103,
        id_aoldb: 1,
        id_vendor: 7,
        id_produkbrand: 4,
        id_produkkategori: 12,
        id_aolprod: 503,
        nama_vendor_produk: 'PT Logitech Indonesia',
        nama_brand_produk: 'Logitech',
        nama_kategori_produk: 'Aksesori',
        nomor_produk: 'PRD-003',
        nama_produk: 'Logitech MX Master 3S Wireless Mouse',
        jenis_produk: 'Barang',
        barcode_produk: '899555444333',
        keterangan_produk: 'Ergonomic performance wireless mouse',
        aktif_produk: true,
        konversi_unit1: 1,
        konversi_unit2: 0,
        konversi_unit3: 0,
        konversi_unit4: 0,
        konversi_unit5: 0,
        rasio_unit1: 1,
        rasio_unit2: 1,
        rasio_unit3: 1,
        rasio_unit4: 1,
        rasio_unit5: 1,
        gramasi_produk: 141,
        panjang_produk_kecil: 12,
        lebar_produk_kecil: 8,
        tinggi_produk_kecil: 5,
        panjang_produk_besar: 25,
        lebar_produk_besar: 20,
        tinggi_produk_besar: 10,
        gambar_produk: '',
        minim_beli_unit1: 2,
        minim_stok_unit1: 10,
        log_aolcat_id: 3,
        log_aolven_id: 3,
        created_at: '2026-07-22T10:00:00Z',
        updated_at: '2026-07-22T10:00:00Z',
        deleted_at: null
      },
      {
        id: 4,
        id_aoldatabase: 104,
        id_aoldb: 1,
        id_vendor: 8,
        id_produkbrand: 5,
        id_produkkategori: 10,
        id_aolprod: 504,
        nama_vendor_produk: 'PT Apple Indonesia',
        nama_brand_produk: 'Apple',
        nama_kategori_produk: 'Laptop',
        nomor_produk: 'PRD-004',
        nama_produk: 'MacBook Pro 16 M3 Max 36GB 1TB',
        jenis_produk: 'Barang',
        barcode_produk: '899111222333',
        keterangan_produk: 'Professional Apple Silicon laptop',
        aktif_produk: false,
        konversi_unit1: 1,
        konversi_unit2: 0,
        konversi_unit3: 0,
        konversi_unit4: 0,
        konversi_unit5: 0,
        rasio_unit1: 1,
        rasio_unit2: 1,
        rasio_unit3: 1,
        rasio_unit4: 1,
        rasio_unit5: 1,
        gramasi_produk: 2140,
        panjang_produk_kecil: 35.5,
        lebar_produk_kecil: 24.8,
        tinggi_produk_kecil: 1.68,
        panjang_produk_besar: 45,
        lebar_produk_besar: 35,
        tinggi_produk_besar: 8,
        gambar_produk: '',
        minim_beli_unit1: 1,
        minim_stok_unit1: 1,
        log_aolcat_id: 4,
        log_aolven_id: 4,
        created_at: '2026-07-22T11:00:00Z',
        updated_at: '2026-07-22T11:00:00Z',
        deleted_at: null
      }
    ];
    return of(dummyDtos);
  }
}
