export interface UserdataRinciDto {
  id: number;
  id_userdata: number | null;
  nik_user: string;
  npwp_user: string;
  kk_user: string;
  nama_user: string;
  tgllahir_user: string;
  alamat_user: string;
  village_id: number | null;
  district_id: number | null;
  regency_id: number | null;
  province_id: number | null;
  latlong_alamat_user: string;
  image_ktp: string;
  image_npwp: string;
  image_kk: string;
  jenis_jaminan: string;
  nomor_jaminan: string;
  image_jaminan: string;
  image_doclegal_satu: string;
  image_doclegal_dua: string;
  lock_legal: boolean;
  emergency_relasi: string;
  emergency_nama: string;
  emergency_handphone: string;
  emergency_alamat: string;
  jenjang_pendidikan: string;
  jurusan_pendidikan: string;
  created_at?: string;
  updated_at?: string;
}
