export interface HariKerja {
  id: number;
  siklusKerja: string;
  harike: string;
  mingguke: number | null;
  bulanke: number | null;
  tahunke: number | null;
  namaHariLokal: string;
  namaBulanLokal: string;
  nameDay: string;
  nameMonth: string;
  tanggalHarikerja: Date;
  hari1: Date;
  hari2: Date;
  hari3: Date;
  hari4: Date;
  hari5: Date;
  hari6: Date;
  hari7: Date;
  hari8: Date;
  hari9: Date;
  hari10: Date;
  hari11: Date;
  hari12: Date;
  hari13: Date;
  hari14: Date;
  hari15: Date;
  hari16: Date;
  hari17: Date;
  hari18: Date;
  hari19: Date;
  hari20: Date;
  hari21: Date;
  hari22: Date;
  hari23: Date;
  hari24: Date;
  hari25: Date;
  hari26: Date;
  hari27: Date;
  hari28: Date;
  hari29: Date;
  hari30: Date;
  hari31: Date;
  createdAt?: Date;
  updatedAt?: Date;
}
