export interface PelangganDto {
  id: number;
  id_aoldatabase: number | null;
  id_aoldb: number | null;
  id_cabang: number | null;
  id_aolcust: number | null;
  id_aolsales: number | null;
  id_jangkapiutang: number | null;
  id_pelanggankategori: number | null;
  nomor_pelanggan: string;
  nama_pelanggan: string;
  siklus_kunjungan: string;
  hari_kunjungan: string;
  id_hargajual: number | null;
  id_hargadiskon: number | null;
  id_hargapromo: number | null;
  id_hargapaket: number | null;
  id_hargamomen: number | null;
  id_piutangplafon: number | null;
  id_piutangmomen: number | null;
  aktif_pelanggan: boolean;
  price_pelanggan: string;
  log_aolcat_id: number | null;
  log_aolbranch_id: number | null;
  log_aolsales_id: number | null;
  log_aolterm_id: number | null;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string | null;
}
