export interface KunjunganDto {
  id: number;
  id_aoldatabase: number | null;
  id_aoldb: number | null;
  id_cabang: number | null;
  id_userdata: number | null;
  id_pelanggan: number | null;
  id_rutekunjung: number | null;
  id_aolcust: number | null;
  kode_kunjungan: string;
  tanggal_kunjungan: string;
  id_kunjunganjual: number | null;
  nilai_kunjungan_jual: number | null;
  id_kunjungantagih: number | null;
  nilai_kunjungan_tagih: number | null;
  nilai_tagih_tunai: number | null;
  nilai_tagih_transfer: number | null;
  nilai_tagih_cekgiro: number | null;
  nilai_total_tagih: number | null;
  status_jual: string;
  status_tagih: string;
  info_tidak_jual: string;
  info_tidak_tagih: string;
  stsjual: boolean;
  ststagih: boolean;
  latlong: string;
  kunjungan_selesai: boolean;
  created_at?: string;
  updated_at?: string;
}
